In [1]:
"""""
NumPy is not considered a framework. It is a library or package in Python that provides functionality for numerical computing.
In general, frameworks provide a complete structure or set of tools for developing applications in a specific domain or for solving a particular problem. 
They often include libraries like NumPy as components to support specific functionalities"""
import numpy as np 
import time

In [5]:
a = np.zeros(4);
print(f"npzeros(4) : a = {a}, a shape = {a.shape}, a data type = a {a.dtype}")
a = np.zeros((4,));
print(f"np.zeros(4,) : a = {a}, a shape = {a.shape}, a data type = a {a.dtype}")
a = np.random.random_sample(4); #Taking 4 randoms number in list
print(f"np.random.random_sample(4) : a = {a}, a shape = {a.shape}, a data type = a {a.dtype}")

npzeros(4) : a = [0. 0. 0. 0.], a shape = (4,), a data type = afloat64
np.zeros(4,) : a = [0. 0. 0. 0.], a shape = (4,), a data type = afloat64
np.random.random_sample(4) : a = [0.81612496 0.78016374 0.13377178 0.32343973], a shape = (4,), a data type = afloat64


In [6]:
a = np.arange(4); # To see their index number
print(f"np.arange(4) : a = {a}, a shape = {a.shape}, a data type = a {a.dtype}")
a = np.random.rand(4);# Taking 4 randoms number in list
print(f"np.random.rand(4) : a ={a}, a shape = {a.shape}, a data type = a {a.dtype}")

np.arange(4) : a = [0 1 2 3], a shape = (4,), a data type = a int32
np.random.rand(4) : a =[0.61657782 0.46671974 0.82361273 0.32619626], a shape = (4,), a data type = a float64


In [7]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
print (f"a[2].shape: {a[2].shape} a2 = {a[2]}, Accessing an element return a scalar ")
print(f"a[-1] = {a[1]}")
try:
    c=a[10]
except Exception as e:
    print("The error message you will see is: ")
    print(e)

a[2].shape: () a2 = 2, Accessing an element return a scalar 
a[-1] = 1
The error message you will see is: 
index 10 is out of bounds for axis 0 with size 10


In [34]:
a = np.arange(10)
print(f"a       ={a}")

c = a[2:7:1]; # a[startpoint, stoppoint, step by number]
print("a[2:7:1]= ", c)
c = a[2:7:2];
print("a[2:7:2]= ", c)
c = a[1:8:8];
print("a[1:8:8]= ", c)
c = a[3:]; # bring all elements after 3 and also included 3.
print("a[3:] = ", c)
c = a[:3];
print("a(:3 )= ", c)# bring all elements before 3 and not included 3.
c = a[:];
print("a(:)= ", c) # Now let's see all together elements!! As same with a[0:10:1]
c = a[0:10:1];
print("a[0:10:1]= ", c) # See what happends :D 

a       =[0 1 2 3 4 5 6 7 8 9]
a[2:7:1]=  [2 3 4 5 6]
a[2:7:2]=  [2 4 6]
a[1:8:8]=  [1]
a[3:] =  [3 4 5 6 7 8 9]
a(:3 )=  [0 1 2]
a(:)=  [0 1 2 3 4 5 6 7 8 9]
a[0:10:1]=  [0 1 2 3 4 5 6 7 8 9]


In [45]:
a = np.array([1,2,3,4]); #Here is number of god list operator... ARRAY FUNC!!
print("a list = ", a) # Hmm.. Looks similar with other print right? Lets deep analyst by Chatgpt :D 
print(f"a list =  {a}") # Go down to analyze both differences :) (Nothing :D) It is just a show different way.
# Both methods will output the same result, displaying the string "a list =" followed by the value of a. 
#The choice between the two options depends on personal preference or the specific requirements of the code you are writing.
b = -a # We did negative values in our list values :) 
print("b = -a           :" , b)# I will prefer to use because of I get used this option...
b = np.sum(a) # Numpy library little bit good to show what we need to know about numpy !! Sum(function)
print("Sum of a list values--> " , b)
b = np.mean(a) # Meam funtion :)
print("Mean of a list values--> ", b)
b = a**2 # What you think square we do not want to right 2 times *2*2...
# It will calculate each values square list first element of list 1**2 = 1x1= 1,... 4**2= 4x4 = 16
print("Square of each list values! ", b) 

a list =  [1 2 3 4]
a list =  [1 2 3 4]
b = -a           : [-1 -2 -3 -4]
Sum of a list values-->  10
Mean of a list values-->  2.5
Square of a list values!  [ 1  4  9 16]


In [51]:
### Let use some adding stuff with using 2 array lists (2 vectors)
a = np.array([1,2,3,4]) # Looks simple. Determine the first list values as a step 1
b = np.array([-1,-2,3,4]) # Here we go second list values Step 2
print("Calculate both vectors elements: ", a+b)
# Letss say we have different vector this one has 2 values not 4.
c = np.array([1,2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

Calculate both vectors elements:  [0 0 6 8]
The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


In [58]:
## Scalar vectorrs : Regular number using for our list of values. use the math sign like '+,*,/,-'
a = np.array([1,2,3,4])
print("a= ", a)
b= 4+a
print("4+a--> ", b)
b= 5*a
print("b= 5* a--> ", b)
b= 5-a
print("b = 5-a --> ", b)
b= a/2
print("b = a/2--> ", b)


a=  [1 2 3 4]
4+a-->  [5 6 7 8]
b= 5* a-->  [ 5 10 15 20]
b = 5-a -->  [4 3 2 1]
b = a/2-->  [0.5 1.  1.5 2. ]


In [60]:
### Vector dot Product is little bit complex in math but you just need to know how it is work thats all.
## Lets see in the example if you have 2 matrix one is a[(1,2,3,4)], other b[(1,2,3,4)]
## we need to do dot product
## first step take first value both of them a[(1)], b[(1)]
## second step multipy both value 1x1=1
## then keep first element 1
## we are gonna do all of the other element same process elementsby following like: [(1,4,9,16)]
## Then Lets use the dot product formula continue. 
## 1+4+9+16= 30
## our result will come 30 :) 

## Lets implement our code block now :) 

def my_dot(a,b): # define as a my_dot name. this my_dot class has 2 different vector. a and b.
    """
   Compute the dot product of two vectors
 
    Args:
      a (ndarray (n,)):  input vector 
      b (ndarray (n,)):  input vector with same dimension as a
    
    Returns:
      x (scalar): 
    """
    x=0 #Empty storage case :) 
    for i in range(a.shape[0]):
        x = x+a[i] *b[i]
        # what happened in here. Simply use x as a storage begining point is 0. Its means empty lets fill the our storage.
        # x = 0  + a[1] * b[1] x1=a[1]b[1] Then go storage for first element x= x1,x2,...xn 
        # then count how many element you have it.
    return x ## Count steps and make same equation until the finishhin !!!


In [62]:
## Now lets take some regular to put our list and show whats going on over there.
a = np.array([1,2,3,4])
b = np.array([-1,-2,4,2])
print("a and b dot product: " , my_dot(a,b))

a and b dot product:  15


In [67]:
# Time to use numpy library !! 
a = np.array([1,2,3,4])
b = np.array([-1,-2,4,2])
c = np.dot(a,b)
print("Numpy example first try  np.dot(a,b): ", c, "    &    np.dot(a,b).shape = ",c.shape)
### Lets calculate cross 
c = np.dot(b,a)
print("Numpy example first try  np.dot(b,a): ", c, "    &    np.dot(b,a).shape = ",c.shape)
## It is intersting result coming with actually proof. :) 
#It means when you change 2 vectors by using dot product, there were nothing change 

Numpy example first try  np.dot(a,b):  15     &    np.dot(a,b).shape =  ()
Numpy example first try  np.dot(b,a):  15     &    np.dot(b,a).shape =  ()


In [73]:
# Lets compare which one is fastest.
np.random.seed(1)
a = np.random.rand(1000000) ## need to use large data
b = np.random.rand(1000000) ## both of them.

tic = time.time() # capture start time
c = np.dot(a, b) # We use library numpy in here. 
toc = time.time() #capture end time

print("np.dot(a, b) =", format(c, '.4f')) # it will take 4 digit number after comma
print("Vectorized version duration: {:.4f} ms".format(1000 * (toc - tic)))

tic = time.time() # capture start time
c = my_dot(a,b) # We use class which called my_dot in here for loop 
toc = time.time() # capture end time

print("np.dot(a, b) =", format(c, '.4f')) # it will take 4 digit number after comma
print("loop version duration: {:.4f} ms".format(1000 * (toc - tic)))
## In the output you can see clearly loop version duration is timely cost more than numpy lib.'
del(a); del(b) # remove these big arrays from memory

np.dot(a, b) = 249825.0234
Vectorized version duration: 0.0000 ms
np.dot(a, b) = 249825.0234
loop version duration: 519.5088 ms


In [79]:
# vector vector example
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1],w)

print("X[1] has shape ", X[1].shape)
print("w has shape ", (w.shape))
print("c has shape ", (c.shape))

X[1] has shape  (1,)
w has shape  (1,)
c has shape  ()


In [81]:
#How to create 2d or nd arrays.
a = np.zeros((1,5))
print("a shape= " ,a.shape,"a = ", a)

a = np.zeros ((2,1))
print("a shape = ", a.shape, " a= ", a)

a = np.random.random_sample((1,1))
print("a shape = ", a.shape, " a = ", a)

a shape=  (1, 5) a =  [[0. 0. 0. 0. 0.]]
a shape =  (2, 1)  a=  [[0.]
 [0.]]
a shape =  (1, 1)  a =  [[0.03762516]]


In [83]:
# Npy routnes which allocate memport and fill with user features values
a = np.array([[5], [4], [3]])
print("a shape =", a.shape, "np.array: a = ", a)
a = np.array ([[5],
              [4],
              [3]]);
print("a shape = ", a.shape, "np.array: a = ", a)



a shape = (3, 1) np.array: a =  [[5]
 [4]
 [3]]
a shape =  (3, 1) np.array: a =  [[5]
 [4]
 [3]]


In [85]:
# vector indexing operations...
a = np.arange(6).reshape(-1, 2) #reshape is a convenient way to create matrix
print("a.shape: ", a.shape, "\na= ", a)
# access an element
print("\na[2,0].shape: ", a[2,0].shape, "a[2,0]= " , a[2,0],
     "type(a[2,0])= ", type(a[2,0]))
#access a row
print("a[2].shape: ", a[2].shape, "a[2]: ", a[2], "type(a[2])= ", type(a[2]))


a.shape:  (3, 2) 
a=  [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape:  () a[2,0]=  4 type(a[2,0])=  <class 'numpy.int32'>
a[2].shape:  (2,) a[2]:  [4 5] type(a[2])=  <class 'numpy.ndarray'>


In [88]:
#vector 2-D slicing operations
a = np.arange(20).reshape(-1,10)
print("a= \n", a)

# acces 5 consecutive elements (start: stop: step)
print("a[0, 2:7:1]= ", a[0, 2:7:1], ", a[0, 2:7:1].shape= ", a[0, 2:7:1].shape, "a 1-d aray")
print("a[:, 2:7:1]= \n", a[:, 2:7:1], ", a[:, 2:7:1].shape= ", a[:, 2:7:1].shape, "a 2-d aray")

#access all elements
print("a[:, :]= \n", a[:,:], ", a[:,:].shape= ", a[:,:].shape)

# access all elements in one row (very common usage)
print("a[1,:]= ", a[1:], ", a[1,:],shape= ", a[1,:].shape, "a 1-D array")
# same as 
print("a[1] = ", a[1], ", a[1].shape= ", a[1].shape, "a 1-D array")

a= 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1]=  [2 3 4 5 6] , a[0, 2:7:1].shape=  (5,) a 1-d aray
a[:, 2:7:1]= 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] , a[:, 2:7:1].shape=  (2, 5) a 2-d aray
a[:, :]= 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] , a[:,:].shape=  (2, 10)
a[1,:]=  [[10 11 12 13 14 15 16 17 18 19]] , a[1,:],shape=  (10,) a 1-D array
a[1] =  [10 11 12 13 14 15 16 17 18 19] , a[1].shape=  (10,) a 1-D array
