### Numpy Library

***NUMPY IS FASTER THAN BASIC PYTHON. BECAUSE NUMPY IS WRITTEN BY C LANGUAGE. C LANGUAGE IS EASY TO INGERATION ASSEMBLY LANGUAGE.***

In [24]:
import numpy as np

## numpy vs python basics

In [25]:
## Python numpy lib using

In [26]:
x = np.array([1,2,3,4,5])

In [27]:
print(x)

[1 2 3 4 5]


In [28]:
import time

In [29]:
start_time = time.time()

In [30]:
a = np.arange(100000)

In [31]:
a **2

array([         0,          1,          4, ..., 1409465417, 1409665412,
       1409865409], dtype=int32)

In [39]:
time_1 = time.time() - start_time

In [40]:
print(time_1)

31.375853776931763


In [33]:
## Basic Python Using

In [34]:
start_time_2 = time.time()

In [35]:
l = range(100000)

In [36]:
[index **2 for index in l]

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801,
 10000,
 10201,
 10404,
 10609,
 10816,
 11025,
 11236,
 11449,
 11664,
 11881,
 12100,
 12321,
 12544,
 12769,
 12996,
 13225,
 13456,
 13689,
 13924,
 14161,
 14400,
 14641,
 14884,
 15129,
 15376,
 15625,
 15876,
 16129,
 16384,
 16641,
 16900,
 17161,
 17424,
 17689,
 17956,
 18225,
 18496,
 18769,
 19044,
 19321,
 19600,
 19881,
 20164,
 2

In [37]:
time_2 = time.time() - start_time_2

In [38]:
print(time_2 / time_1)

0.2956298669341131


### Creating ndarray with using numpy

In [42]:
w = np.array([5,6,7,8,9])

In [43]:
print(w) ## Create 1-d array vectorization

[5 6 7 8 9]


In [44]:
print(type(w))

<class 'numpy.ndarray'>


In [55]:
print(w.shape) ## Return as a tuple and show the count of element in same dimention.

(5,)


In [56]:
print(w.size) ## Shows that count of elements. 

5


In [57]:
print(w.ndim) ## Shows the dimension.

1


In [58]:
print(w.nbytes) ## Size of our array in memory

20


In [59]:
print(w.dtype) ## Type of element data types.

int32


## 2-D array

In [62]:
y = np.array([[12,23,34], [41,52,63]])

In [63]:
print(type(y))

<class 'numpy.ndarray'>


In [64]:
print(y.shape) ## Return as a tuple and show the count of element in same dimention. 2 is columns and 3 is rows.

(2, 3)


In [65]:
print(y.size) ## Shows that count of elements. 

6


In [66]:
print(y.ndim) ## Shows the dimension.

2


In [67]:
print(y.nbytes) ## Size of our array in memory

24


In [68]:
print(y.dtype) ## Type of element data types.

int32


In [69]:
z = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(z)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [70]:
print(z.shape)

(2, 2, 2)


In [71]:
print(z.ndim)

3


In [72]:
x = np.array([1,2,3])

In [74]:
print(x.dtype)

int32


In [75]:
y = np.array([1,'2',3])

In [85]:
print(y.dtype) ## This is U11 character string. UpCasting

<U11


In [86]:
z = np.array([1,2.0,3])

In [87]:
print(z.dtype) ## It changes automatically upcasting

float64


In [94]:
x = np.array([3, 4.0, 5]) ## If you put float value, it will return automatically float64 type of data.

In [95]:
print(x)

[3. 4. 5.]


In [96]:
print(x.dtype)

float64


### We can change the data type or we can determine the data type ownself

In [101]:
x = np.array([3,4,5], dtype = np.int)
print(x)
print(x.dtype)

[3 4 5]
int32


C:\Users\Mustafa\AppData\Local\Temp\ipykernel_21012\1321835609.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array([3,4,5], dtype = np.int)


In [102]:
y = np.array([3, 4, 5], dtype = np.float)
print(y)
print(y.dtype)

[3. 4. 5.]
float64


C:\Users\Mustafa\AppData\Local\Temp\ipykernel_21012\4270860435.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y = np.array([3, 4, 5], dtype = np.float)


In [103]:
z = np.array([3,4,5], dtype= np.complex)
print(z)
print(z.dtype)

[3.+0.j 4.+0.j 5.+0.j]
complex128


C:\Users\Mustafa\AppData\Local\Temp\ipykernel_21012\179252699.py:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  z = np.array([3,4,5], dtype= np.complex)


***We can say this issue downcast. We are taking the float type of value with int type of value***

In [104]:
x = np.array([1.2, 2.7, 3.8], dtype= np.int)
print(x)
print(x.dtype)

[1 2 3]
int32


C:\Users\Mustafa\AppData\Local\Temp\ipykernel_21012\988212851.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array([1.2, 2.7, 3.8], dtype= np.int)


In [106]:
x = np.array ([1,2,3,4], dtype=np.float)
print(x)
print(x.dtype)

[1. 2. 3. 4.]
float64


C:\Users\Mustafa\AppData\Local\Temp\ipykernel_21012\3628500105.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array ([1,2,3,4], dtype=np.float)


***We can change data type with different method***

In [107]:
x = np.array(x, dtype = complex) 

In [108]:
print(x)
print(x.dtype)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex128


***We can also use .astype method to change type of datas.***

In [109]:
x= x.astype(np.complex)
print(x)
print(x.dtype)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex128


C:\Users\Mustafa\AppData\Local\Temp\ipykernel_21012\2797784807.py:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x= x.astype(np.complex)


In [112]:
x1 = np.array([1,2,3], dtype = np.int)
x2 = np.array([5.2, 2.8, 4.9], dtype= np.float)

C:\Users\Mustafa\AppData\Local\Temp\ipykernel_21012\3373102323.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x1 = np.array([1,2,3], dtype = np.int)
C:\Users\Mustafa\AppData\Local\Temp\ipykernel_21012\3373102323.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/de

In [113]:
print(x1 + x2)
print((x1 + x2).dtype)

[6.2 4.8 7.9]
float64


In [114]:
x = np.sqrt(np.array([-1, 9, 4], dtype = np.float)) ## we need to do complex type of data. because if you want to get -1 square of root it need to be two different value. 
print(x)

[nan  3.  2.]


C:\Users\Mustafa\AppData\Local\Temp\ipykernel_21012\3619506021.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.sqrt(np.array([-1, 9, 4], dtype = np.float))
C:\Users\Mustafa\AppData\Local\Temp\ipykernel_21012\3619506021.py:1: RuntimeWarning: invalid value encountered in sqrt
  x = np.sqrt(np.array([-1, 9, 4], dtype = np.float))


In [116]:
x= np.sqrt(np.array([-1,9,4], dtype = np.complex)) ## Now all is good.
print(x)

[0.+1.j 3.+0.j 2.+0.j]


C:\Users\Mustafa\AppData\Local\Temp\ipykernel_21012\4040523975.py:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x= np.sqrt(np.array([-1,9,4], dtype = np.complex)) ## Now all is good.


In [122]:
print(x.real) ## We are gonna get real part. Example it will gives first value before + sign. 0., 3., 2.
print(x.imag) ## we are gonna get imag part.  for example it will gives, part of +1.j +0.j + 0.j
print((x.real).dtype) ## We can see in here part of real data type
print((x.imag).dtype) ## We can see in here part of image data type

[0. 3. 2.]
[1. 0. 0.]
float64
float64


### Save and Load Method

In [123]:
x = np.array([5, 9, 3.2, 16])

In [127]:
np.save('ndarray_1', x) ## We save ndarray_1 as a file. 

In [128]:
y = np.load('ndarray_1.npy') ## We can use in here load to get our saving file.
print(y)
print(y.shape)

[ 5.   9.   3.2 16. ]
(4,)


## Embedded Python/Numpy

In [129]:
x = np.array([3, 9, 8])
print(x)
print(type(x))

[3 9 8]
<class 'numpy.ndarray'>


### np.zeros and np.ones

In [138]:
x1 = np.zeros(4)
print(x1)
print(x1.dtype) ## It will return float type of data

[0. 0. 0. 0.]
float64


In [139]:
y1 = np.ones(4)
print(y1)
print(y1.dtype)

[1. 1. 1. 1.]
float64


**We can also create multi-D array.**

In [219]:
x2 = np.zeros((2,3,4), dtype = np.int) ## We create in here 2 different, 3 columns and 4 rows array. We create 3-d array..
print(x2) 

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


C:\Users\Mustafa\AppData\Local\Temp\ipykernel_21012\3653699308.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x2 = np.zeros((2,3,4), dtype = np.int) ## We create in here 2 different, 3 columns and 4 rows array. We create 3-d array..


In [220]:
y2 = np.ones((3,2)) ## We create this function 2-d
print(y2)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


***We can use this kinds of function to manipulate data.***

### np.full

In [221]:
x = np.full((2,3), 10) ## We create what we wanna put inside of the matrix. First we create columns and rows, then we create what we need to put in matrix.
print(x)
print(x.dtype)

[[10 10 10]
 [10 10 10]]
int32


In [223]:
x = np.full((2,3), 10.0) ## In this particular example we can use 10.0 it will return automatically float type of array.
print(x)
print(x.dtype)

[[10. 10. 10.]
 [10. 10. 10.]]
float64


In [224]:
y = 10.0 * np.ones((2,3))

In [225]:
z = 10.0 + np.zeros((2,3))

In [226]:
print(y)

[[10. 10. 10.]
 [10. 10. 10.]]


In [227]:
print(z)

[[10. 10. 10.]
 [10. 10. 10.]]


### np.empty() ,np.fill()

In [228]:
x = np.empty((2,2)) ## It will come random values.

In [229]:
print(x)

[[0.         2.33333333]
 [4.66666667 7.        ]]


In [230]:
x.fill(3) ## We are gonna use .fill() for what number we wanna fill in array.
print(x)

[[3. 3.]
 [3. 3.]]


### np.eye()

***We can create unit matrix in here.***

In [231]:
x = np.eye(4) ## It will bring diagonal matrix :) 
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [232]:
y = np.eye(5,4) ## It will comes with last one zero values..

In [233]:
print(y)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [234]:
x = np.eye(6)

In [235]:
print(x)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [236]:
y = np.eye(6, k=1) ## It will shift "1" one unit right..

In [237]:
print(y)

[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]


In [238]:
z = np.eye(6, k=-2) ## It will shift "1" two unit left...

In [239]:
print(z)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


### np.identity()

In [240]:
x = np.identity(5) # We create also identity method to create unit matrix
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### np.diag()

In [241]:
x = np.diag([4,7,11,3]) ## We can determine diagonal numbers changing with our values.
print(x)

[[ 4  0  0  0]
 [ 0  7  0  0]
 [ 0  0 11  0]
 [ 0  0  0  3]]


### np.arange()

In [242]:
x = np.arange(10) # Creating 1 dimension array with index numbers.Or we can say that [0,10) in mathematically
print(x) # it will count 0 to 10 because of te numpy knows this range between 0 to 10. Like, np.arange(0,10) 

[0 1 2 3 4 5 6 7 8 9]


In [243]:
y = np.arange(4,9)
print(y)

[4 5 6 7 8]


In [244]:
z = np.arange(3, 22, 4) # Let say here 3 different parameter using.... When you decide to use these 3 different parameters you can think like (start,stop,step)
print(z) ## [3+0, 3+4, 7+4, 11+4, 15+4] 

[ 3  7 11 15 19]


### np.linspace()

In [245]:
x = np.linspace(0, 15, 10) # linspace gives you a number which is using 10 limited random numbers. so we can say here (start,stop,limit)
print(x)

[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.         11.66666667 13.33333333 15.        ]


In [246]:
x = np.linspace (0,7,4)
print(x)

[0.         2.33333333 4.66666667 7.        ]


In [247]:
x = np.linspace(0,1) # If we did not put any number limit. it will count automatically 50...
print(x)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [248]:
x = np.linspace(0,4, endpoint = False) # We dont take last element in array.
print(x)

[0.   0.08 0.16 0.24 0.32 0.4  0.48 0.56 0.64 0.72 0.8  0.88 0.96 1.04
 1.12 1.2  1.28 1.36 1.44 1.52 1.6  1.68 1.76 1.84 1.92 2.   2.08 2.16
 2.24 2.32 2.4  2.48 2.56 2.64 2.72 2.8  2.88 2.96 3.04 3.12 3.2  3.28
 3.36 3.44 3.52 3.6  3.68 3.76 3.84 3.92]


**WE CAN USE LINSPACE() METHOD TO USE DECIMAL NUMBER SUCH AS 0.12, 0.123**

### np.reshape()

In [249]:
x= np.arange(20)

In [250]:
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [251]:
y = np.reshape(x, (4,5)) ## It will change dimension of array. !!! if we create 5,5 array we will get error. becasue 5x5 array need to be 25 elements.

In [252]:
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [253]:
x = np.arange(32)

In [254]:
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]


In [255]:
 y =  np.reshape(x, (2,4,4)) 

In [256]:
print(y)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]


In [257]:
x = np.linspace(0, 19, 20)

In [258]:
print(x)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]


In [259]:
y = np.reshape(x,(2,10))

In [260]:
print(y)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]


In [261]:
z = np.linspace(0, 19, 20).reshape(2,10)

In [262]:
print(z)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]


### np.random.random()

In [263]:
x = np.random.random((2,3)) ## it will come with [0,1)

In [264]:
print(x)

[[0.60207006 0.50279822 0.05510848]
 [0.98576987 0.34706233 0.29441386]]


### np.random.radint()

In [265]:
x = np.random.randint(3, 12, size=(3,2)) ### it will come any int number take between 3 and 12 but the array need to be 3 columns and 2 rows.
print(x)

[[ 4  8]
 [11  3]
 [ 4  3]]


In [266]:
x = np.arange(5)

In [267]:
print(x)

[0 1 2 3 4]


In [268]:
print(x[0])

0


In [269]:
print(x[2])

2


In [270]:
print(x[5-1])

4


In [271]:
print(x[-1])

4


In [272]:
print(x[-5])

0


In [273]:
x [2]= 200 

In [274]:
print()

In [275]:
print(x)

[  0   1 200   3   4]


In [276]:
print(x[2])

200


In [277]:
x = np.arange(12).reshape(3,4)

In [278]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [279]:
print(x[0,0])

0


In [280]:
print(x[0,1])

1


In [281]:
print(x[0,2])

2


In [282]:
print(x[1,3])

7


In [283]:
print(x[2,2])

10


In [284]:
x [0,0] = 100
print(x[0,0])

100


In [285]:
print(x)

[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [286]:
x = np.arange(6) 

In [287]:
print(x)

[0 1 2 3 4 5]


### np.delete()

In [288]:
y = np.delete(x, [0,1])

In [289]:
print(y)
print (x)

[2 3 4 5]
[0 1 2 3 4 5]


In [290]:
# axis =0 row - axis = 1 column  for 2-d array

In [291]:
x =  np.arange(16).reshape(4,4)

In [292]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [293]:
x = np.delete(x, 1, axis = 0)
print(x)

[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]


In [294]:
x =np.delete(x, [0,2], axis=1)

In [295]:
print(x)

[[ 1  3]
 [ 9 11]
 [13 15]]


### np.append()

In [296]:
x = np.arange(5)

In [297]:
print(x)

[0 1 2 3 4]


In [298]:
x = np.append(x, 100)

In [299]:
print(x)

[  0   1   2   3   4 100]


In [300]:
x = np.append(x, [200,300])

In [301]:
print(x)

[  0   1   2   3   4 100 200 300]


In [302]:
x = np.arange(9).reshape(3,3)

print(x)

In [305]:
x = np.append(x, [[100, 200, 300]], axis= 0)
print(x)

[[  0   1   2]
 [  3   4   5]
 [  6   7   8]
 [100 200 300]]


In [308]:
x = np.append(x, [[50], [60], [70], [80]], axis = 1)

In [309]:
print(x)

[[  0   1   2  50]
 [  3   4   5  60]
 [  6   7   8  70]
 [100 200 300  80]]


### np.insert

*** np.insert(array, index, element, axis for 2d)

In [337]:
x = np.arange(5)

In [338]:
print(x)

[0 1 2 3 4]


In [339]:
x = np.insert(x, 1, [7,8]) 

In [340]:
print(x)

[0 7 8 1 2 3 4]


In [341]:
x = np.arange(9).reshape(3,3)

In [342]:
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [343]:
x = np.insert (x, 1, [30, 40, 50], axis = 0)

In [344]:
print(x)

[[ 0  1  2]
 [30 40 50]
 [ 3  4  5]
 [ 6  7  8]]


In [347]:
x = np.insert(x, 0, [100,200,300, 400], axis = 1)

In [348]:
print(x)

[[100   0   1   2]
 [200  30  40  50]
 [300   3   4   5]
 [400   6   7   8]]


### np.stack()

In [349]:
x = np.arange(3)

In [350]:
print(x)

[0 1 2]


In [351]:
y = np.arange(9).reshape(3,3)

In [352]:
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [353]:
z = np.vstack((x,y)) ## Vertical = vstack ... 

In [354]:
print(z)

[[0 1 2]
 [0 1 2]
 [3 4 5]
 [6 7 8]]


In [356]:
w =np.arange(9).reshape(3,3)

In [357]:
print(w)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [360]:
t = np.hstack((y,w)) ## horizontal = hstack....

In [361]:
print(t)

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [6 7 8 6 7 8]]


## Slicing

***ndarray[start:end]***, *ndarray[start:]*, **ndarray[:end]**

In [362]:
x = np.arange(10)

In [363]:
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [365]:
print(x[2:6])

[2 3 4 5]


In [366]:
print(x[4:])

[4 5 6 7 8 9]


In [367]:
print(x[:6])

[0 1 2 3 4 5]


In [368]:
print(x[:-1])

[0 1 2 3 4 5 6 7 8]


In [369]:
print(x[:-5])

[0 1 2 3 4]


In [370]:
print(x[-2:])

[8 9]


In [371]:
print(x[-3:])

[7 8 9]


In [374]:
print(x[-4:-2])

[6 7]


In [375]:
print(x[-6:-1])

[4 5 6 7 8]


***2d array slicing***

In [376]:
x = np.arange(25).reshape(5,5)

In [377]:
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [378]:
y = x[0:3, 1:4]
print(y)

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [379]:
z = x[2:]
print(z)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [380]:
t = x[::]
print(t)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [381]:
v = x[:,3:]
print(v)

[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]


In [382]:
x =  np.arange(9).reshape(3,3)

In [383]:
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [384]:
y = x[1:2, 0:2]

In [385]:
print(y)

[[3 4]]


In [386]:
y[0,0] = 100
print(y)

[[100   4]]


In [387]:
print(x)

[[  0   1   2]
 [100   4   5]
 [  6   7   8]]


In [388]:
print(np.shares_memory(x,y))

True


In [389]:
x= np.arange(16).reshape(4,4)

In [390]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [391]:
y = np.copy(x[0:3, 1:3]) 

In [392]:
print(y)

[[ 1  2]
 [ 5  6]
 [ 9 10]]


In [394]:
print(np.shares_memory(x,y)) ## It shows us both of us shared different memory.

False


In [395]:
y[0,0] = 100
print(y)
print(x)

[[100   2]
 [  5   6]
 [  9  10]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [396]:
z = x[1:2, 1:2].copy()
print(z)

[[5]]


In [397]:
print(np.shares_memory(x,z))

False


In [398]:
x = np.linspace(1,21,11) 

In [399]:
print(x)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21.]


In [400]:
y = np.array([2,4,7]) 

In [401]:
print(y)

[2 4 7]


In [403]:
print(x[y]) ### 2,4,7 INDEX NUMBER ARRAY WILL COME FROM ARRAY X.

[ 5.  9. 15.]


### Fancy Indexing

In [404]:
x = np.arange(25).reshape(5,5) 

In [405]:
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [406]:
y = np.array([1,2])
print(y)

[1 2]


In [407]:
print(x[y,:])

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [408]:
z = np.array([2,3])

In [409]:
print(z)

[2 3]


In [410]:
print(x[z,:])

[[10 11 12 13 14]
 [15 16 17 18 19]]


In [411]:
print(x[z,2:])

[[12 13 14]
 [17 18 19]]


In [412]:
print(x[z,:2])

[[10 11]
 [15 16]]


In [414]:
print(x[:,z]) 

[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]
 [22 23]]


In [415]:
w = x[z,:]

In [416]:
print(w)

[[10 11 12 13 14]
 [15 16 17 18 19]]


In [417]:
w[0,0] = 100
print(w)

[[100  11  12  13  14]
 [ 15  16  17  18  19]]


In [419]:
print(x) ## if you use sub array with using another array, it doesn't effect main array. Its called Fancy indexing.

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [420]:
print(np.shares_memory(x,w))

False


### Boolean indexing

In [421]:
 x = np.arange(10)

In [422]:
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [423]:
print(x[x %2 == 0])

[0 2 4 6 8]


In [424]:
print(x[x % 3 == 0])

[0 3 6 9]


In [426]:
print(x[x+1 == 4])

[3]


In [427]:
z = x[(x % 5 == 0)] 

In [428]:
print(z)

[0 5]


In [429]:
z[0] = 100

In [430]:
print(z)

[100   5]


In [431]:
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [432]:
print(np.shares_memory(x,z))

False


In [433]:
x = np.random.randint(10, size = 10)
y = np.random.randint(10, size = 10)

In [434]:
print(x)
print(y)

[5 3 6 9 6 8 7 0 8 7]
[2 0 7 6 9 4 1 0 6 5]


In [440]:
print(x>y) ## It will check in side of array elements. if x is greater than y, boolean will return true otherwise will return zero(False).

[ True  True False  True False  True  True False  True  True]


In [437]:
print(type(x>y))

<class 'numpy.ndarray'>


In [439]:
print((x>y).dtype)

bool


In [441]:
print(np.all(x>y)) # Check all elements are same condition.

False


In [442]:
print(np.any(x>y)) # Check any elements are same condition

True


In [443]:
x = np.linspace(1,21,11)

In [444]:
print(x)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21.]


In [447]:
mask = (x % 3 == 0)

In [448]:
print(mask)

[False  True False False  True False False  True False False  True]


In [449]:
print(type(mask))

<class 'numpy.ndarray'>


In [450]:
print((mask).dtype)

bool


In [451]:
print(x[mask])

[ 3.  9. 15. 21.]


In [452]:
x[mask] = -3
print(x)

[ 1. -3.  5.  7. -3. 11. 13. -3. 17. 19. -3.]


In [453]:
x = np.array([2,5,3,6,9]) 

In [454]:
y = np.array([6,1,8,7,3])

In [457]:
print(np.intersect1d(x,y)) ## np.intersect1d() will bring from two different arrays which are same elements as 1d array...

[3 6]


In [458]:
z = np.intersect1d(x,y)

In [459]:
print(z)

[3 6]


In [465]:
print(np.setdiff1d(x,y))# bring differences between x to y.
x_diff = np.setdiff1d(x,y)
print(x_diff)

[2 5 9]
[2 5 9]


In [466]:
print(np.setdiff1d(y,x)) # bring differences between y to x.
y_diff = np.setdiff1d(y,x)
print(y_diff)

[1 7 8]
[1 7 8]


In [467]:
print(np.union1d(x,y))

[1 2 3 5 6 7 8 9]


In [470]:
nod_elements= np.union1d(x,y) ## Bring all non duplicate element if it is duplicated take one of those.
print(nod_elements)

[1 2 3 5 6 7 8 9]


In [472]:
print(np.in1d(x,y)) ## It will compare two array if the same values both of them take elements order by x.

[False False  True  True False]


In [473]:
print(np.in1d(y,x)) ## It will compare two array if the same values both of them take elements order by y.

[ True False False False  True]


In [475]:
x = np.array([2,5,3,6,9,3,6,5,0]) ## It will bring all unique one. Not copy of elementss!!
print(np.unique(x))

[0 2 3 5 6 9]


## Sort

In [476]:
x = np.random.randint(1, 10, size = (10,))

In [477]:
print(x)

[9 5 9 5 4 6 1 8 4 8]


In [478]:
print(np.sort(x)) ## it will sort by assending.

[1 4 4 5 5 6 8 8 9 9]


In [479]:
print(x)

[9 5 9 5 4 6 1 8 4 8]


In [480]:
y = np.random.randint(1, 10, size = (10,))

In [481]:
print(y)

[1 1 8 6 1 4 3 1 1 1]


In [484]:
y.sort()

In [485]:
print(y)

[1 1 1 1 1 1 3 4 6 8]


In [486]:
## 2-D ARRAY

In [497]:
d = np.random.randint(1,10, size=(5,5)) 

In [498]:
print(np.sort(d, axis = 0)) # axis= 0  means sorted by rows.
print(np.sort(d, axis = 1)) # axis= 1  means sorted by columns.

[[1 2 3 4 3]
 [5 2 5 5 6]
 [5 3 5 6 6]
 [5 5 6 6 7]
 [7 5 7 6 8]]
[[2 3 5 6 6]
 [3 5 5 6 7]
 [1 3 6 7 7]
 [4 5 5 5 6]
 [2 5 5 6 8]]


## Element - Wise, Array - Wise

In [500]:
x = np.random.randint(1,10, size= (5,))

In [501]:
print(x)

[6 8 7 9 7]


In [502]:
y = np.random.randint(1,10, size= (5,))

In [503]:
print(y)

[8 3 4 1 6]


In [504]:
print(x + y)

[14 11 11 10 13]


In [505]:
print(np.add(x,y))

[14 11 11 10 13]


In [506]:
print(type(x + y))

<class 'numpy.ndarray'>


In [507]:
print(type(np.add(x,y)))

<class 'numpy.ndarray'>


In [508]:
print(x - y)
print(np.subtract(x,y))

[-2  5  3  8  1]
[-2  5  3  8  1]


In [509]:
print(x * y)
print(np.multiply(x,y))

[48 24 28  9 42]
[48 24 28  9 42]


In [510]:
print(x/y)
print(np.divide(x,y))

[0.75       2.66666667 1.75       9.         1.16666667]
[0.75       2.66666667 1.75       9.         1.16666667]


In [511]:
print(x+3)
print(x-3)
print(x*3)
print(x/3)

[ 9 11 10 12 10]
[3 5 4 6 4]
[18 24 21 27 21]
[2.         2.66666667 2.33333333 3.         2.33333333]


In [512]:
print(x==y)

[False False False False False]


In [515]:
z =np.random.randint(1,10 , size = (6,))

In [516]:
print(z)

[6 8 8 3 8 7]


In [517]:
print(x+z) ### arithmatic values  size need to be same. example (1-d=1-d and also size = size)or need to be broadcast.

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [518]:
print(np.array_equal(x,y))

False


In [519]:
t = np.array([1,2,3])
d = np.array([1,2,3])

In [520]:
print(np.array_equal(t,d))

True


## Mathmetical Functions

In [528]:
print(np.sqrt(x))

[2.44948974 2.82842712 2.64575131 3.         2.64575131]


In [523]:
print(np.power(x,3))

[216 512 343 729 343]


In [524]:
print(np.exp(x))

[ 403.42879349 2980.95798704 1096.63315843 8103.08392758 1096.63315843]


In [525]:
print(np.log(x))

[1.79175947 2.07944154 1.94591015 2.19722458 1.94591015]


In [530]:
print(np.cos(x))

[ 0.96017029 -0.14550003  0.75390225 -0.91113026  0.75390225]


In [531]:
print(np.sum(x))

37


In [536]:
x = np.random.randint(1,10, size = (9,)).reshape(3,3)

In [537]:
print(x)

[[1 2 8]
 [7 2 8]
 [4 6 1]]


In [539]:
print(np.sum(x)) ## Total elements number in array...

39


In [540]:
print(x.sum(axis=0)) # rows

[12 10 17]


In [541]:
print(x.sum(axis=1)) #columns

[11 17 11]


In [542]:
print(x.min())

1


In [543]:
print(x.max())

8


In [544]:
print(x.mean())

4.333333333333333


In [545]:
print(x.std())

2.788866755113585


In [550]:
print(x.argmin()) ## Min element ordered Index number

0


In [551]:
print(x.argmax()) ## Max element index Number

2


## Statistical Functions

In [552]:
x= np.random.randint(1,10, size= (8,))

In [553]:
print(x)

[5 9 4 5 3 1 9 3]


In [554]:
print(x.mean())

4.875


In [556]:
print(np.median(x))

4.5


In [557]:
print(x.std())

2.666341125962693


In [558]:
y= np.random.randint(1,10, size= (4,3))
print(y)

[[2 9 5]
 [4 9 2]
 [3 4 3]
 [3 8 3]]


In [559]:
print(y.mean(axis = 0)) # rows mean

[3.   7.5  3.25]


In [560]:
print(y.mean(axis = 1)) # columns mean

[5.33333333 5.         3.33333333 4.66666667]


In [561]:
print(np.median(y, axis = 0)) # rows median

[3.  8.5 3. ]


In [562]:
print(np.median(y, axis =1)) # columns median

[5. 4. 3. 3.]


In [563]:
print(y.std (axis = 0)) # rows standard dev.

[0.70710678 2.06155281 1.08972474]


### Broadcasting 

In [569]:
x= np.random.randint(1,10, size= (3,))
print(x)
y= np.random.randint(1,10, size= (3,2)) ## We could not able to do this because of we dont have 3. elements in second matrix.
print(y)

[5 7 6]
[[3 4]
 [5 5]
 [4 6]]


In [570]:
print(x +y)

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [571]:
x= np.random.randint(1,10, size= (3,1))
print(x)
y= np.random.randint(1,10, size= (1,3)) 
print(y) ## We can do this because it will come with 3x3 matrix.

[[7]
 [9]
 [2]]
[[3 4 5]]


In [572]:
print(x+y)

[[10 11 12]
 [12 13 14]
 [ 5  6  7]]
